import { ApiProperty } from '@nestjs/swagger';
import { User } from 'src/user/entities/user.entity';

export class LoginResponseDto {
  @ApiProperty({
    description: 'JWT generated by login.',
    example: 'Put a token here.',
  })
  token: string;

  @ApiProperty({
    description: 'Data of authenticated data.',
  })
  user: User;
}
